# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 591)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 771, 551))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.events_list_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.events_list_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.events_list_label.setTextFormat(QtCore.Qt.PlainText)
        self.events_list_label.setAlignment(QtCore.Qt.AlignCenter)
        self.events_list_label.setObjectName("events_list_label")
        self.verticalLayout_2.addWidget(self.events_list_label)
        self.events_list = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.events_list.setObjectName("events_list")
        self.verticalLayout_2.addWidget(self.events_list)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.new_event_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.new_event_label.setAlignment(QtCore.Qt.AlignCenter)
        self.new_event_label.setObjectName("new_event_label")
        self.verticalLayout.addWidget(self.new_event_label)
        self.new_event_field = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.new_event_field.setObjectName("new_event_field")
        self.verticalLayout.addWidget(self.new_event_field)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.horizontalLayoutWidget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.verticalLayout.addWidget(self.dateTimeEdit)
        self.new_event_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.new_event_btn.setObjectName("new_event_btn")
        self.verticalLayout.addWidget(self.new_event_btn)
        self.line_2 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.delete_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.delete_label.setAlignment(QtCore.Qt.AlignCenter)
        self.delete_label.setObjectName("delete_label")
        self.verticalLayout.addWidget(self.delete_label)
        self.delete_event_field = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.delete_event_field.setObjectName("delete_event_field")
        self.verticalLayout.addWidget(self.delete_event_field)
        self.delete_evenet_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.delete_evenet_btn.setObjectName("delete_evenet_btn")
        self.verticalLayout.addWidget(self.delete_evenet_btn)
        self.line_3 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.safe_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.safe_label.setAlignment(QtCore.Qt.AlignCenter)
        self.safe_label.setObjectName("safe_label")
        self.verticalLayout.addWidget(self.safe_label)
        self.safe_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.safe_btn.setObjectName("safe_btn")
        self.verticalLayout.addWidget(self.safe_btn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.events_list_label.setText(_translate("MainWindow", "Список событий"))
        self.new_event_label.setText(_translate("MainWindow", "Новое событие"))
        self.new_event_btn.setText(_translate("MainWindow", "Добавить"))
        self.delete_label.setText(_translate("MainWindow", "Удалить событие"))
        self.delete_evenet_btn.setText(_translate("MainWindow", "Удалить"))
        self.safe_label.setText(_translate("MainWindow", "Создать отчет"))
        self.safe_btn.setText(_translate("MainWindow", "Сохранить"))

